# MCP GSuite Integration - Docker Compose
# WT-MCPGS-1.0

version: '3.8'

services:
  mcp-gsuite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wt-mcp-gsuite
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - USER_GOOGLE_EMAIL=${USER_GOOGLE_EMAIL}
      - GOOGLE_PSE_API_KEY=${GOOGLE_PSE_API_KEY}
      - MCP_SERVER_PORT=8000
      - MCP_TRANSPORT=http
      - NODE_ENV=production
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - gsuite-data:/app/data
    networks:
      - wombat-track-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-gsuite.rule=PathPrefix(`/api/mcp/gsuite`)"
      - "traefik.http.services.mcp-gsuite.loadbalancer.server.port=8000"
      - "project=WT-MCPGS-1.0"
      - "service=mcp-gsuite"

volumes:
  gsuite-data:
    driver: local

networks:
  wombat-track-network:
    external: true