openapi: 3.0.3
info:
  title: Governance Logs API
  description: Enhanced Governance Log API for Wombat Track platform
  version: 1.0.0
servers:
  - url: /api
    description: Local API server
paths:
  /admin/governance_logs:
    get:
      summary: List governance logs
      description: Retrieve governance logs with optional filtering and pagination
      parameters:
        - in: query
          name: q
          description: Full-text search query
          schema:
            type: string
        - in: query
          name: phase_id
          description: Filter by phase ID
          schema:
            type: string
        - in: query
          name: step_id
          description: Filter by step ID
          schema:
            type: string
        - in: query
          name: entryType
          description: Filter by entry type (Decision, Change, Review, Architecture, etc.)
          schema:
            type: string
        - in: query
          name: classification
          description: Filter by classification
          schema:
            type: string
        - in: query
          name: from
          description: Filter logs from this date
          schema:
            type: string
            format: date-time
        - in: query
          name: to
          description: Filter logs up to this date
          schema:
            type: string
            format: date-time
        - in: query
          name: page
          description: Page number (1-based)
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: page_size
          description: Number of items per page
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 50
      responses:
        '200':
          description: Successfully retrieved governance logs
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GovernanceLog'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
    post:
      summary: Create governance log
      description: Create a new governance log entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGovernanceLogRequest'
      responses:
        '201':
          description: Governance log created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernanceLog'
        '400':
          description: Invalid request data
  /admin/governance_logs/{id}:
    get:
      summary: Get governance log by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Governance log retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernanceLog'
        '404':
          description: Governance log not found
    put:
      summary: Update governance log
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGovernanceLogRequest'
      responses:
        '200':
          description: Governance log updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovernanceLog'
        '404':
          description: Governance log not found
    delete:
      summary: Archive governance log
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Governance log archived successfully
        '404':
          description: Governance log not found
  /admin/governance_logs/search:
    get:
      summary: Search governance logs
      description: Advanced search with semantic capabilities
      parameters:
        - in: query
          name: q
          required: true
          description: Search query for semantic search
          schema:
            type: string
        - in: query
          name: limit
          description: Maximum number of results
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Search results retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GovernanceLogSearchResult'
                  total:
                    type: integer
components:
  schemas:
    GovernanceLog:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        timestamp:
          type: string
          format: date-time
          description: When the log entry was created
        entryType:
          type: string
          description: Type of governance entry
          enum: [Decision, Change, Review, Architecture, Process, Risk, Compliance, Quality, Security, Performance]
        summary:
          type: string
          description: Brief summary of the governance event
        gptDraftEntry:
          type: string
          nullable: true
          description: AI-generated detailed entry
        classification:
          type: string
          nullable: true
          description: Classification category
        related_phase:
          type: string
          nullable: true
          description: Related phase ID
        related_step:
          type: string
          nullable: true
          description: Related step ID
        linked_anchor:
          type: string
          nullable: true
          description: Memory plugin anchor reference
        created_by:
          type: string
          description: User or system that created the entry
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
        links:
          type: array
          items:
            $ref: '#/components/schemas/LogLink'
          description: Related links
      required:
        - id
        - timestamp
        - entryType
        - summary
        - created_by
    LogLink:
      type: object
      properties:
        target_id:
          type: string
          description: Target entity ID
        link_type:
          type: string
          description: Type of relationship
          enum: [reference, dependency, impact, follow_up]
        created_at:
          type: string
          format: date-time
    CreateGovernanceLogRequest:
      type: object
      properties:
        entryType:
          type: string
          enum: [Decision, Change, Review, Architecture, Process, Risk, Compliance, Quality, Security, Performance]
        summary:
          type: string
          minLength: 10
          maxLength: 500
        gptDraftEntry:
          type: string
          nullable: true
        classification:
          type: string
          nullable: true
        related_phase:
          type: string
          nullable: true
        related_step:
          type: string
          nullable: true
        linked_anchor:
          type: string
          nullable: true
        links:
          type: array
          items:
            type: object
            properties:
              target_id:
                type: string
              link_type:
                type: string
                enum: [reference, dependency, impact, follow_up]
      required:
        - entryType
        - summary
    UpdateGovernanceLogRequest:
      type: object
      properties:
        summary:
          type: string
          minLength: 10
          maxLength: 500
        gptDraftEntry:
          type: string
          nullable: true
        classification:
          type: string
          nullable: true
        related_phase:
          type: string
          nullable: true
        related_step:
          type: string
          nullable: true
        linked_anchor:
          type: string
          nullable: true
    GovernanceLogSearchResult:
      allOf:
        - $ref: '#/components/schemas/GovernanceLog'
        - type: object
          properties:
            relevance_score:
              type: number
              description: Search relevance score (0-1)
            matched_fields:
              type: array
              items:
                type: string
              description: Fields that matched the search query
    Pagination:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
        page_size:
          type: integer
          minimum: 1
        total_pages:
          type: integer
          minimum: 0
        total_items:
          type: integer
          minimum: 0
        has_next:
          type: boolean
        has_previous:
          type: boolean
      required:
        - page
        - page_size
        - total_pages
        - total_items
        - has_next
        - has_previous