name: Notion Sync Test

on:
  push:
    branches: [main, feature/wt-notion-sync]
  pull_request:
    branches: [main]

jobs:
  test-notion-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript build check
        run: npx tsc --noEmit

      - name: Lint Notion utilities
        run: npx eslint src/utils/notion*.ts src/utils/driveMemorySync.ts --format=compact

      - name: Test Notion client instantiation
        run: |
          node -e "
          const { createNotionClient } = require('./src/utils/notionClient.ts');
          console.log('✅ Notion client can be instantiated');
          "

      - name: Validate database schemas
        run: |
          node -e "
          const { NotionDatabaseCreator } = require('./src/utils/notionDatabaseCreator.ts');
          const schemas = [
            NotionDatabaseCreator.getProjectSchema(),
            NotionDatabaseCreator.getPhaseSchema(),
            NotionDatabaseCreator.getPhaseStepSchema(),
            NotionDatabaseCreator.getEnhancedGovernanceSchema()
          ];
          schemas.forEach((schema, i) => {
            if (!schema.name || !schema.properties) {
              throw new Error(\`Schema \${i} is invalid\`);
            }
          });
          console.log('✅ All database schemas are valid');
          "

      - name: Test DriveMemory sync utilities
        run: |
          node -e "
          const { DriveMemorySync } = require('./src/utils/driveMemorySync.ts');
          const config = {
            notionToken: 'dummy-token',
            databaseIds: { governance: 'dummy-id' }
          };
          new DriveMemorySync(config);
          console.log('✅ DriveMemory sync utilities can be instantiated');
          "

      - name: Test Gizmo polling script
        run: |
          node -e "
          const { pollClaudeMessages } = require('./src/utils/pollClaudeMessages.ts');
          console.log('✅ Gizmo polling script can be imported');
          "

      - name: Run Notion sync dry-run test
        run: npx tsx scripts/test-drivememory-sync.ts || echo "⚠️ Sync test completed (may require live Notion token)"
        continue-on-error: true

  security-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for secrets in code
        run: |
          echo "🔍 Checking for hardcoded secrets..."
          if grep -r "secret_" src/ scripts/ --include="*.ts" --include="*.js"; then
            echo "❌ Found potential hardcoded secrets"
            exit 1
          fi
          echo "✅ No hardcoded secrets found"

      - name: Validate environment variable usage
        run: |
          echo "🔍 Checking environment variable usage..."
          if grep -r "process\.env\." src/ scripts/ --include="*.ts" --include="*.js" | grep -v "process\.env\.NOTION_TOKEN" | grep -v "process\.env\.NOTION_"; then
            echo "⚠️ Found environment variables other than NOTION_* - please verify"
          fi
          echo "✅ Environment variable usage validated"