name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: wombat-track/package-lock.json

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path:  < /dev/null | 
            ~/.npm
            wombat-track/node_modules
          key: \${{ runner.os }}-node-\${{ hashFiles('wombat-track/package-lock.json') }}
          restore-keys: |
            \${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ./wombat-track
        run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: wombat-track/package-lock.json

      - name: Install dependencies
        working-directory: ./wombat-track
        run: npm ci

      - name: Run ESLint
        working-directory: ./wombat-track
        run: npm run lint || true

      - name: Run TypeScript check
        working-directory: ./wombat-track
        run: npx tsc --noEmit || true

  security:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --severity-threshold=high --file=wombat-track/package.json
        env:
          SNYK_TOKEN: \${{ secrets.SNYK_TOKEN }}

  build:
    needs: [lint, security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: wombat-track/package-lock.json

      - name: Install dependencies
        working-directory: ./wombat-track
        run: npm ci

      - name: Build project
        working-directory: ./wombat-track
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: wombat-track/dist

  notify:
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Notify via PR comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: \${{ github.event.pull_request.number }}
          body: |
            ## 🤖 CI Build Status
            
            | Check | Status |
            |-------|--------|
            | Lint | \${{ needs.lint.result }} |
            | Security | \${{ needs.security.result }} |
            | Build | \${{ needs.build.result }} |
            
            [View workflow run](\${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }})

      - name: Slack notification
        if: github.ref == 'refs/heads/main'
        uses: 8398a7/action-slack@v3
        with:
          status: \${{ job.status }}
          text: 'Build \${{ job.status }} for \${{ github.repository }}'
          webhook_url: \${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK_URL: \${{ secrets.SLACK_WEBHOOK }}
