name: Claude Scaffold Enhanced

on:
  workflow_dispatch:
    inputs:
      phase_id:
        description: 'Phase ID'
        required: true
        type: string
      notify_slack:
        description: 'Send Slack notification'
        required: false
        type: boolean
        default: true

jobs:
  scaffold:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: wombat-track/package-lock.json
          
      - name: Run scaffold script
        id: scaffold
        run: |
          chmod +x wombat-track/scripts/claude/scaffold.sh
          OUTPUT=$(./wombat-track/scripts/claude/scaffold.sh "${{ github.event.inputs.phase_id }}")
          echo "output=$OUTPUT" >> $GITHUB_OUTPUT
          
      - name: Create PR comment
        if: github.event.pull_request
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🤖 Claude Scaffold Complete
            
            **Phase ID**: `${{ github.event.inputs.phase_id }}`
            **Triggered by**: @${{ github.actor }}
            **Status**: ✅ Success
            
            <details>
            <summary>Scaffold Output</summary>
            
            ```
            ${{ steps.scaffold.outputs.output }}
            ```
            
            </details>
            
      - name: Update commit status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              description: 'Claude scaffold completed',
              context: 'claude/scaffold'
            })
            
      - name: Slack notification
        if: inputs.notify_slack && always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Claude Scaffold ${{ job.status }}
            Phase: ${{ github.event.inputs.phase_id }}
            Actor: ${{ github.actor }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          
  deploy-after-scaffold:
    needs: scaffold
    if: success()
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: staging
      phase_id: ${{ github.event.inputs.phase_id }}
    secrets:
      DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}